### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sheep1965**

### CODE REVIEW

**Comment by sheep1965** [comment]
hihi

**Review by Zeyecx — COMMENTED** [review]
Fine

**Comment by viown** [comment]
This is by far the best contribution I've ever seen.

**Comment by Zeyecx** [comment]
> This is by far the best contribution I've ever seen.

Thanks :)

**Comment by Zeyecx** [comment]
@viowm That's because I don't have such a little devil as a companion :)

**Comment by Zeyecx** [comment]
@viown That's because I don't have such a little devil as a companion :)

**Pull request merged**
