### PR TITLE
Added OOP

### PR DESCRIPTION
**Pull request by viown**

### CODE REVIEW

**Comment by viown** [comment]
Also added some features such as checking if the user is currently online, their join date, wins/losses, and a few other stuff.

**Comment by Zeyecx** [comment]
Nice. That's a nice idea :)

**Comment by Zeyecx** [comment]
I'll have a look at the PyLinter later. Then this one will also be successful.

https://github.com/Zeyecx/lichesspy/runs/2623760427#step:5:10

**Comment by viown** [comment]
changing __init__.py to
`from lichesspy.user import User` should fix it.

**Comment by Zeyecx** [comment]
There are a few other things. They are fixed now. It is also included in the new release.

**Pull request merged**
